### ISSUE TITLE
Switch off CircleCI

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-demos#294]
The project already started to move to GH CI. This issue is to suggest completing the move off CCI.

**Comment by ajbozarth** [comment]
As I've mentioned in previous oqs calls, after wrapping up #298 I plan to start work moving the CI to GitHub. This seems to be the primary issue for tracking that work, but #213 and #284 seem to duplicate the general move to GitHub Actions work. In addition #300 #301 and #308 might be straight forward to include spending how the process goes. 

In preparation for this work I just wanted to note down the relevant issues for tracking

**Comment by ajbozarth** [comment]
> This may be simple to extend to all demos but I wouldn't be surprised if more problems occur than you may feel comfortable doing in one PR

Given I built and tested all my work in #298 on both macOS and a RHEL VM, I believe this should just be a config, but as you said well see what happened when I get into it

> The goal of creating https://github.com/open-quantum-safe/oqs-demos/issues/294 and https://github.com/open-quantum-safe/oqs-demos/issues/284 was to motivate others to contribute smaller, more focused PRs instead of solving everything in one go tackling https://github.com/open-quantum-safe/oqs-demos/issues/213.

That makes sense, once I get into it I'll see how creating the different parts of the CI flow and maybe decide to separate the work as the issues are separated.

The my initial primary goal is to move the automated testing CI off on circleCI and onto GitHub Actions, cross platform support and deployment will either come after or hand-in-hand depending on how it goes (I've never wrote GH Actions from scratch, only edited existing configs, so hopefully I'll be learning new tricks along the way)

**Comment by ajbozarth** [comment]
A bit of an update on my progress here, I've been playing with GitHub actions on my fork in my free moments the past few weeks and as of yesterday I have a working build and test example (using openssl3 demo). I'll share some implementation notes below:

Based on my research the best way to handle projects like ours, with many "subproject", is for each subproject (ie demo) to have it's own workflow yaml that is only triggered when there are edits to it's own dir.

I'm initially focused on getting build and test CI working, without including the push CI. My focus on the build and test is to move the current build and test steps from CircleCI and make sure they run on both linux/amd64 and linux/arm64 and on both pinned releases and latest liboqs/oqsprovider code.

You can take a peek at some of my work at https://github.com/ajbozarth/oqs-demos/actions and https://github.com/ajbozarth/oqs-demos/tree/testci but it's pretty messy since I had to push every time I edit for the actions to trigger to test them. Since then I've found how to trigger workflows via VSCode with pushing, so I may clean up my work and open a draft PR today since I may no longer need to push to run workflows.

**Comment by ajbozarth** [comment]
> I may clean up my work and open a draft PR today since I may no longer need to push to run workflows.

After confirming I can trigger local workflow files against branches on my fork without pushing I decided to open #321 as a draft with my current progress

**Comment by ajbozarth** [comment]
>  consolidate the requirements and streamline collaboration

@Hayyaaf That was my intention with [my comment above](https://github.com/open-quantum-safe/oqs-demos/issues/294#issuecomment-2445374991), to make this issue the tracking issue for my CI updates work and have [my PR](https://github.com/open-quantum-safe/oqs-demos/pull/321) close this and the other issues it handles. I don't believe we should close the other issues before the specific feature they request is complete though. In general now that my PR is open it would be the best place to hold discussion on the CI work. (This is based on my personal open-source history, I'll defer to @baentsch if he wants to follow a different process for this project)

**Comment by baentsch** [comment]
> I propose opening a single issue to consolidate the requirements and streamline collaboration. What are your thoughts?

Agreed with @ajbozarth on tracking all issues related to the CCI -> GH CI move. My link re: warnings above seemed simple enough to do at the same time (update an actions version) but feel free to keep/solve it separately (but be aware that one of you may need to rebase, depending on what's done when). I step aside and let you handle as you see fit.
