### ISSUE TITLE
Fix OpenVPN failures

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-demos#330]
#321 introduced a test error for OpenVPN. This issue is to track fixing this.

**Comment by ajbozarth** [comment]
Since I did do some preliminary research on this and got nowhere I will share that here:

I identified when the test started failing by looking at previous runs https://github.com/open-quantum-safe/oqs-demos/actions/workflows/openvpn.yml then I tried looking into anything in the Dockerfile or scripts that doesn't use a pinned version of a lib, I tested if it was the base ubuntu image (it wasn't) and I tested if it was a race-condition by increasing the sleep length in the test script (and it still failed).

Though the above ideas might still have weight, I don't know enough about the demo to dig further, I did identify that it is the creation of the server container that is failing in the test.sh, the client container is successfully created, but left in a bad state due to the lack of server container.

**Comment by baentsch** [comment]
fyi, the problem had to do with a now stricter docker permissions model - fixed in #336
